### ISSUE TITLE
Method declarations in define-generics always show up as uncovered

### ISSUE THREAD

**Issue by lexi-lambda** [florence/cover#59]
Generic interface declarations always show up as uncovered even though they should be ignored. See this for an example:
https://coveralls.io/builds/2130076/source?filename=alexis%2Fcollection%2Fcountable.rkt

**Comment by florence** [comment]
Hey!

quick thing: you may want to add the `-b` flag to your travis.yaml. That will prevent your info.rkt's from showing up in your reports.

Two things: If you look at the html coverage report (which is much more accurate, as it is expression based coverage) you will see that only two words are uncovered: both countables. `length` is covered because it appears in the body of the define-generics. the countables argument is not, because it does not appear. I'm not sure why the countable on the define-generics line is uncovered...

but this is what I would expect from a define-generics from. It should not be ignored, as it leaves behind code for the default implementations. We have similar issues with for loops (see #27). Eventually cover will provide a way for libraries to say "ignore this syntax", but thats a post 2.0 thing.

**Comment by lexi-lambda** [comment]
Ah, yes, you are correct. It's not a big problem, but I figured I'd note it here for completeness.

As a side note, even with `-b` enabled, apparently my scribble documentation is still being *run*. This would be fine, but it counts the sandboxed examples as tests for coverage purposes, which is really not what I want. ;)

Is there a good way to prevent those from being run entirely?

**Comment by florence** [comment]
Yes. Cover supports options in your info.rkt to skip files. Specifically it respects `raco test`s `test-omit-paths` and has its own `cover-omit-paths`. This differs from the `-n` flag in that it will skip running those file, instead of just ignoring them in the coverage report.

a `raco doc cover` will give you more information on the command line arguments.

**Comment by florence** [comment]
(As a matter of fact, cover is mostly compatible with the arguments and info.rkt configs for raco test)

**Comment by florence** [comment]
Fixed by #81
