### ISSUE TITLE
Need to fail on the system* call

### ISSUE THREAD

**Issue by rpless** [florence/cover#7]
It seems like we don't throw an error if exec curl.sh fails.
Evidence: https://travis-ci.org/rpless/rkt-ci-example/builds/45453934#L277

**Comment by florence** [comment]
This is difficult to fix, as curl still exits with code 0 if the request responds with a non 200 code. The proper fix for this would be to implement multipart HTTP requests ourselves, so that cover works in normal windows environments. I will take a look at it next time I get my hands on bottle of port.
